# List of popular fast-moving Indian stocks (NSE) suitable for options and intraday trading.
NIFTY_50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBI.NS", "BHARTIARTL.NS", "LART.NS",
    "KOTAKBANK.NS", "AXISBANK.NS", "ASIANPAINT.NS", "HCLTECH.NS", "BAJFINANCE.NS",
    "MARUTI.NS", "SUNPHARMA.NS", "TATASTEEL.NS", "ULTRACEMCO.NS", "JSWSTEEL.NS",
    "GRASIM.NS", "ADANIENT.NS", "ADANIPORTS.NS", "TITAN.NS", "POWERGRID.NS",
    "NTPC.NS", "INDUSINDBK.NS", "ONGC.NS", "HDFCLIFE.NS", "DIVISLAB.NS",
    "WIPRO.NS", "COALINDIA.NS", "BPCL.NS", "M&M.NS", "HEROMOTOCO.NS",
    "EICHERMOT.NS", "HINDALCO.NS", "JIOFIN.NS", "TATACONSUM.NS", "TATAMOTORS.NS",
    "NESTLEIND.NS", "APOLLOHOSP.NS", "BAJAJ-AUTO.NS", "CIPLA.NS", "DRREDDY.NS",
    "BRITANNIA.NS", "BPCL.NS", "BAJAJFINSV.NS", "EICHERMOT.NS", "SHRIRAMFIN.NS"
]

BANK_NIFTY_TICKERS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS",
    "INDUSINDBK.NS", "AUBANK.NS", "BANDHANBNK.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS",
    "PNB.NS", "BANKBARODA.NS"
]

HIGH_BETA_OPTIONS_TICKERS = [
    "RELIANCE.NS", "SBIN.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "HDFCBANK.NS",
    "ICICIBANK.NS", "AXISBANK.NS", "INFY.NS", "TCS.NS", "BAJFINANCE.NS",
    "BAJAJFINSV.NS", "ADANIENT.NS", "ADANIPORTS.NS", "MARUTI.NS", "M&M.NS",
    "INDHOTEL.NS", "DLF.NS", "GMRINFRA.NS", "HAL.NS", "BEL.NS",
    "PFC.NS", "RECLTD.NS", "JINDALSTEL.NS", "COALINDIA.NS", "ONGC.NS"
]

ALL_CATEGORIES = {
    "Nifty 50": NIFTY_50_TICKERS,
    "Bank Nifty": BANK_NIFTY_TICKERS,
    "High Beta / Options Active": HIGH_BETA_OPTIONS_TICKERS
}
